### ISSUE TITLE
[Klient] Ustalenia

### ISSUE THREAD

**Issue by czechue** [typeofweb/sklep#14]
**KA:**

- [x] Mamy plan i ogólny zarys jak mają wyglądać strony:
- Home Page
- Product Page
- Collection Page*
- Collection List*
- Cart
- Checkout
- 404

**Jakie przewidujemy generyczne sekcje:**
- Header
- Footer
- Hero Image with text overlay *
- Collection List
- Featured product
- Testimonials *
- Texts collumn with images *
- Slider *
- Rich text *
- Gallery *
- Logo list *
- Image with text *

`* nie koniecznie do MVP`

**TODO:**

- [x]  spisanie tasków
- [x]  dokument z inspiracjami do ww. komponentów i stron
- [x]  ustalenia co do narzędzi i bibliotek
- [x]  ustalenia co do architektury
